import { Video, Session } from './Types';
import { ApiClient } from './ApiClient';

import fs from 'fs';
import path from 'path';
import { parse } from 'iso8601-duration';
import { askUserChoiche } from './CommandLineParser';
import sanitize from 'sanitize-filename';
import { logger } from './Logger';


function publishedDateToString(date: string) {
    const dateJs = new Date(date);
    const day = dateJs.getDate().toString().padStart(2, '0');
    const month = (dateJs.getMonth() + 1).toString(10).padStart(2, '0');
    const publishedDate = day + '-' + month + '-' + dateJs.getFullYear();

    return publishedDate;
}

function durationToTotalChunks(duration: string) {
    const durationObj = parse(duration);
    const hrs = durationObj['hours'] ?? 0;
    const mins = durationObj['minutes'] ?? 0;
    const secs = Math.ceil(durationObj['seconds'] ?? 0);

    return (hrs * 60) + mins + (secs / 60);
}

export async function getVideoInfo(videoGuids: Array<string>, session: Session, subtitles?: boolean): Promise<Array<Video>> {
    let metadata: Video[] = [];
    let title: string;
    let date: string;
    let totalChunks: number;
    let playbackUrl: string;
    let posterImageUrl: string;
    let captionsUrl: string | undefined;

    const apiClient = ApiClient.getInstance(session);

    for (const GUID of videoGuids) {
        let response = await apiClient.callApi('videos/' + GUID, 'get');

        title = sanitize(response?.data['name']);
        playbackUrl = response?.data['playbackUrls']
            .filter((item: { [x: string]: string; }) =>
                item['mimeType'] == 'application/vnd.apple.mpegurl')
            .map((item: { [x: string]: string }) => {
                return item['playbackUrl'];
            })[0];

        posterImageUrl = response?.data['posterImage']['medium']['url'];
        date = publishedDateToString(response?.data['publishedDate']);
        totalChunks = durationToTotalChunks(response?.data.media['duration']);

        if (subtitles) {
            let captions = await apiClient.callApi(`videos/${GUID}/texttracks`, 'get');

            if (!captions?.data.value.length) {
                captionsUrl = undefined;
            }
            else if (captions?.data.value.length === 1) {
                logger.info(`Found subtitles for ${title}. \n`);
                captionsUrl = captions?.data.value.pop().url;
            }
            else {
                const index = askUserChoiche(captions.data.value.map((item: { language: any; autoGenerated: any; }) => {
                    return `[${item.language}] autogenerated: ${item.autoGenerated}`;
                }));
                captionsUrl = captions.data.value[index].url;
            }
        }

        metadata.push({
            date: date,
            totalChunks: totalChunks,
            title: title,
            outPath: '',
            playbackUrl: playbackUrl,
            posterImageUrl: posterImageUrl,
            captionsUrl: captionsUrl
        });
    }

    return metadata;
}


export function createUniquePath(videos: Array<Video>, outDirs: Array<string>, format: string, skip?: boolean): Array<Video> {

    videos.forEach((video, index) => {
        let title = `${video.title} - ${video.date}`;
        let i: number = 0;

        while (!skip && fs.existsSync(path.join(outDirs[index], title + '.' + format))) {
            title = `${video.title} - ${video.date}_${++i}`;
        }


        video.outPath = path.join(outDirs[index], title + '.' + format);
    });

    return videos;
}
